# Some commands:
#
# docker compose -p rprj-ng -f docker-compose.dev.yml up --build
#
# docker container rm rprj-ng-fe-1 ; docker image rm rprj-ng-fe
# docker container rm rprj-ng-be-1 ; docker image rm rprj-ng-be
# docker container restart rprj-ng-be-1
# docker exec -it rprj-ng-db-1 mariadb -u root --password=mysecret rproject
# docker exec -it rprj-ng-be-1 bash
# docker exec -it rprj-ng-fe-1 bash

services:
  proxy:
    image: nginx:alpine
    ports:
      - "8080:8080"
    volumes:
      - ./proxy/nginx.dev.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - fe
      - be
    restart: unless-stopped

  fe:
    build:
      context: ./fe
      dockerfile: Dockerfile.dev
    volumes:
      - ./fe:/app          # This hides node_modules previously built, so you need the following line
      - /app/node_modules  # Anonymous volume: use node_modules from the image !!
    # healthcheck:
    #   test: ["CMD", "true"]
    #   # test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000"]
    #   interval: 10s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 5s
    depends_on:
      be:
        condition: service_healthy
    environment:
      # - REACT_APP_ENDPOINT=http://localhost:8080/api  # Per connettere FE a BE
      - REACT_APP_API_URL=/api  # Per connettere FE a BE
      # Only for windows to force polling
      - CHOKIDAR_USEPOLLING=true  # Force polling for file changes (fix Windows/Docker)
      - CHOKIDAR_INTERVAL=1000    # Polling interval in ms (1s: balanced, non CPU-heavy)
      - CHOKIDAR_USEPOLLING=watchman  # Optional: if you have watchman installed

  be:
    build:
      context: ./be
      dockerfile: Dockerfile.dev
    expose:
      - "1971"
    # Temporary for external Ollama access from Docker container
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # environment:
    #   - DB_URL=root:mysecret@tcp(mysql:3306)/rproject
    volumes:
      - ./be:/app
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:1971/ping"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 5s
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mariadb:12.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: mysecret
      MYSQL_DATABASE: rproject
    # ports:
    #   - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d  # Mount for init: executes the sql files sorted alphabetically
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "root", "-pmysecret"]
      timeout: 20s
      retries: 10

volumes:
  mysql_data:
