# Some commands:
#
# docker compose -p rprj-ng-dev -f docker-compose.dev.yml up --build
#
# docker container rm rprj-ng-dev-fe-1 ; docker image rm rprj-ng-dev-fe
# docker container rm rprj-ng-dev-be-1 ; docker image rm rprj-ng-dev-be
# docker container restart rprj-ng-dev-be-1
# docker exec -it rprj-ng-dev-db-1 mariadb -u root --password=mysecret rproject
# docker exec -it rprj-ng-dev-be-1 sh
# docker exec -it rprj-ng-dev-fe-1 sh

services:
  proxy:
    image: nginx:alpine
    ports:
      - "8081:8080"
    volumes:
      - ./proxy/nginx.dev.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - fe
      - be
    restart: unless-stopped

  fe:
    build:
      context: ./fe
      dockerfile: Dockerfile.dev
    volumes:
      - ./fe:/app          # This hides node_modules previously built, so you need the following line
      - /app/node_modules  # Anonymous volume: use node_modules from the image !!
    # healthcheck:
    #   test: ["CMD", "true"]
    #   # test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000"]
    #   interval: 10s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 5s
    ports:
      - "3000:3000"
    depends_on:
      be:
        condition: service_healthy
    environment:
      - APP_NAME=R-Project
      - REACT_APP_SITE_TITLE=üêù œÅ-Bee DEV üêù
      # - REACT_APP_ENDPOINT=http://localhost:8080/api  # Per connettere FE a BE
      - REACT_APP_API_URL=/api
      - REACT_APP_HOME_OBJECT_ID=-10 
      # Only for windows to force polling
      - CHOKIDAR_USEPOLLING=true  # Force polling for file changes (fix Windows/Docker)
      - CHOKIDAR_INTERVAL=1000    # Polling interval in ms (1s: balanced, non CPU-heavy)
      - CHOKIDAR_USEPOLLING=watchman  # Optional: if you have watchman installed

  be:
    build:
      context: ./be
      dockerfile: Dockerfile.dev
    expose:
      - "1971"
    ports:
      # This allows to access Swagger UI and API directly from host machine: http://localhost:1971/swagger/index.html
      - "1971:1971"
    # Allow access to host and local subnet IPs
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "external.llama:192.168.1.232"  # Example static IP for external llama server
    environment:
      # Ollama is optional - comment out or leave empty to disable
      - OLLAMA_URL=http://external.llama:11434/api/chat
      - OLLAMA_MODEL="llama3.2:latest"
      # Enable Swagger in development
      - ENABLE_SWAGGER=true
    volumes:
      - be_files:/app/files
      - ./be:/app
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:1971/ping"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 5s
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mariadb:12.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: mysecret
      MYSQL_DATABASE: rproject
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d  # Mount for init: executes the sql files sorted alphabetically
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "root", "-pmysecret"]
      timeout: 20s
      retries: 10
  # pgdb:
  #   image: postgres:18
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_PASSWORD: mysecret
  #     POSTGRES_DB: rproject
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  #     - ./db-postgres:/docker-entrypoint-initdb.d  # Mount for init:
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U postgres"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

volumes:
  be_files:
  mysql_data:
  # pgdata:
