# Some commands:
#
# docker compose -p rprj-ng -f docker-compose.yml up
# docker compose -p rprj-ng -f docker-compose.yml -f docker-compose.dev.yml up
#
# docker container rm rprj-ng-fe-1 ; docker image rm rprj-ng-fe
# docker container rm rprj-ng-be-1 ; docker image rm rprj-ng-be
# docker image prune
# docker exec -it rprj-ng-db-1 mariadb -u root --password=mysecret rproject
# docker exec -it rprj-ng-be-1 sh
# docker exec -it rprj-ng-fe-1 sh

services:
  proxy:
    image: nginx:alpine
    ports:
      - "8080:8080"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - fe
      - be
    restart: unless-stopped

  fe:
    build:
      context: ./fe
      dockerfile: Dockerfile
    expose:
      - "80"
    depends_on:
      - be
    environment:
      - REACT_APP_SITE_TITLE=üêù œÅ-Bee CMS üêù
      - REACT_APP_ENDPOINT=/api
      - REACT_APP_HOME_OBJECT_ID=-10
      - REACT_APP_ENABLE_GOOGLE_OAUTH=false
      - REACT_APP_ENABLE_GITHUB_OAUTH=false

  be:
    build:
      context: ./be
      dockerfile: Dockerfile
    expose:
      - "1971"
    environment:
      # Fill these in for production with your OAuth credentials
      - DB_URL=root:mysecret@tcp(mysql:3306)/rproject
      - GOOGLE_CLIENT_ID=
      - GOOGLE_CLIENT_SECRET=
      - GOOGLE_REDIRECT_URL=
      - GITHUB_CLIENT_ID=
      - GITHUB_CLIENT_SECRET=
      - GITHUB_REDIRECT_URL=
      - APP_NAME=œÅBee
    volumes:
      - be_files:/root/files
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mariadb:12.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: mysecret
      MYSQL_DATABASE: rproject
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d  # Mount for init: executes the sql files sorted alphabetically
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "root", "-pmysecret"]
      timeout: 20s
      retries: 10

volumes:
  be_files:
  mysql_data:
