root = "."
testdata_dir = "testdata"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assets", "tmp", "vendor", "testdata_dir"]
exclude_regex = ["_test.go"]
exclude_undented = false
align_tags = true
log_level = "info"
print_to = "both"
print_line_count = 0

# Sezione build/esecuzione (qui passi gli args!)
[build]
  cmd = "go run ."
  bin = ""  # Non serve bin
  full_bin = "go run . ./config_dev.json"  # Passa arg a go run
  # Opzionale: includi env vars, es. full_bin = "MY_ENV=val ./tmp/main ./config_dev.json"
  include_pkg = false
  include_build_file = false