name: Docker Image CI

env:
  DOCKER_IMAGE_NAME: rprj-ng

permissions:
  contents: write       # I must update the version number
  packages: write       # required to push to GHCR with GITHUB_TOKEN

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Read VERSION file
      id: ver
      run: |
        if [ ! -f VERSION ]; then
          echo "VERSION file not found" >&2
          exit 1
        fi
        # trim newline/carriage returns
        version=$(tr -d '\r\n' < VERSION)
        echo "tag=$version" >> "$GITHUB_OUTPUT"

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push BE image to GHCR
      uses: docker/build-push-action@v4
      with:
        context: ./be
        file: ./be/Dockerfile        # optional if Dockerfile is named Dockerfile in ./be
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/${{ env.DOCKER_IMAGE_NAME }}-be:latest
          ghcr.io/${{ github.repository_owner }}/${{ env.DOCKER_IMAGE_NAME }}-be:${{ steps.ver.outputs.tag }}

    - name: Build and push FE image to GHCR
      uses: docker/build-push-action@v4
      with:
        context: ./fe
        file: ./fe/Dockerfile        # optional if Dockerfile is named Dockerfile in ./be
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/${{ env.DOCKER_IMAGE_NAME }}-fe:latest
          ghcr.io/${{ github.repository_owner }}/${{ env.DOCKER_IMAGE_NAME }}-fe:${{ steps.ver.outputs.tag }}

    - name: Increase version number for the next release
      run: |
        version=$(cat VERSION)
        IFS='.' read -r major minor patch <<< "$version"
        patch=$((patch + 1))
        new_version="$major.$minor.$patch"
        echo "$new_version" > VERSION
        echo "Next version: $new_version"

    - name: Commit and push
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add VERSION
        git commit -m "Bump version to $new_version" || echo "No changes to commit"
        git push

